"""Portable power diode compact model emitter."""

from __future__ import annotations

import math
from textwrap import dedent
from typing import Any

from ..dialects import SUPPORTED_DIALECTS, dialect_suffix
from ..plugins import emitter
from ..schema import DeviceProject


VT_25C = 0.025852


def _clean(text: str) -> str:
    lines: list[str] = []
    for line in text.splitlines():
        lines.append(line if line.startswith("+") else line.lstrip())
    return "\n".join(lines).rstrip() + "\n"


@emitter("diode-basic")
class DiodeBasicEmitter:
    label = "Basic Power Diode Compact Model"
    description = "Portable SPICE diode model with package parasitic starter deck."
    component_profiles = ("diode.power",)

    def emit(self, project: DeviceProject, dialect: str = "common") -> dict[str, str]:
        if dialect not in SUPPORTED_DIALECTS:
            raise ValueError(f"unsupported diode dialect: {dialect}")
        suffix = dialect_suffix(dialect)
        model_file = f"{project.model_name}_diode{suffix}.lib"
        return {
            model_file: _render_model(project, dialect),
            f"{project.model_name}_reverse_recovery_diode{suffix}.cir": _render_reverse_recovery(project, model_file),
        }


@emitter("diode-abm-dynamic")
class DiodeAbmDynamicEmitter:
    label = "Dynamic Diode Behavioral Model"
    description = "Portable diode ABM starter with nonlinear Cj(VR) current and reverse-recovery charge state."
    component_profiles = ("diode.power",)

    def emit(self, project: DeviceProject, dialect: str = "common") -> dict[str, str]:
        if dialect not in SUPPORTED_DIALECTS:
            raise ValueError(f"unsupported diode dialect: {dialect}")
        suffix = dialect_suffix(dialect)
        model_file = f"{project.model_name}_diode_abm{suffix}.lib"
        return {
            model_file: _render_abm_dynamic_model(project, dialect),
            f"{project.model_name}_reverse_recovery_diode_abm{suffix}.cir": _render_reverse_recovery(project, model_file),
        }


def _render_model(project: DeviceProject, dialect: str) -> str:
    name = project.model_name
    params = _diode_parameters(project)
    return _clean(dedent(
        f"""\
        * {name} diode-basic model generated by datasheet2spice
        * Dialect: {dialect}. Uses portable two-terminal SPICE diode primitives.
        * Pins: A K
        .subckt {name} A K
        La A a_lead {params["la_nh"]:g}n
        RpkgA a_lead a_int {params["ra_ohm"]:g}
        Dcore a_int k_int {name}_DIODE
        RpkgK k_int k_lead {params["rk_ohm"]:g}
        Lk k_lead K {params["lk_nh"]:g}n
        .model {name}_DIODE D(Is={params["is_a"]:.6g} N={params["n"]:.6g} Rs={params["rs_ohm"]:.6g} Cjo={params["cjo_pf"]:.6g}p
        + M={params["m"]:.6g} Vj={params["vj_v"]:.6g} Tt={params["tt_ns"]:.6g}n BV={params["bv_v"]:.6g} Ibv={params["ibv_a"]:.6g})
        .ends {name}
        """
    ))


def _render_abm_dynamic_model(project: DeviceProject, dialect: str) -> str:
    name = project.model_name
    params = _diode_parameters(project)
    fwd_current = "0.5*(I(Vsense)+sqrt(I(Vsense)*I(Vsense)+1e-18))"
    reverse_voltage = "0.5*(V(k_int,a_sense)+sqrt(V(k_int,a_sense)*V(k_int,a_sense)+1e-12))"
    reverse_gate = "0.5*(1-tanh(V(a_sense,k_int)/VSMOOTH))"
    cj_expr = f"CJ_SCALE*CJO*(1+{reverse_voltage}/VJ)**(-M)*DDT(V(a_sense,k_int))"
    q_expr = f"V(qrr_state)/TAU - (1-({reverse_gate}))*{fwd_current}"
    recovery_expr = f"-RR_SCALE*({reverse_gate})*V(qrr_state)/TAU"
    return _clean(dedent(
        f"""\
        * {name} diode-abm-dynamic model generated by datasheet2spice
        * Dialect: {dialect}. Behavioral starter for Cj(VR) and reverse-recovery transient checks.
        * Pins: A K
        .subckt {name} A K PARAMS: RR_SCALE={params["rr_scale"]:.6g} CJ_SCALE=1 VSMOOTH=50m
        .param TAU={params["tau_ns"]:.6g}n CJO={params["cjo_pf"]:.6g}p VJ={params["vj_v"]:.6g} M={params["m"]:.6g}
        La A a_lead {params["la_nh"]:g}n
        RpkgA a_lead a_int {params["ra_ohm"]:g}
        Vsense a_int a_sense 0
        Ddc a_sense k_int {name}_DC
        {_behavior_current("cj", "a_sense", "k_int", cj_expr, dialect)}
        {_behavior_current("qrr", "qrr_state", "0", q_expr, dialect)}
        Cqrr qrr_state 0 1
        Rqrr qrr_state 0 1e12
        {_behavior_current("rr", "a_sense", "k_int", recovery_expr, dialect)}
        Rleak a_sense k_int 1e12
        RpkgK k_int k_lead {params["rk_ohm"]:g}
        Lk k_lead K {params["lk_nh"]:g}n
        .model {name}_DC D(Is={params["is_a"]:.6g} N={params["n"]:.6g} Rs={params["rs_ohm"]:.6g} Cjo=1f
        + M={params["m"]:.6g} Vj={params["vj_v"]:.6g} Tt=0 BV={params["bv_v"]:.6g} Ibv={params["ibv_a"]:.6g})
        .ends {name}
        """
    ))


def _behavior_current(name: str, pos: str, neg: str, expr: str, dialect: str) -> str:
    if dialect in {"common", "pspice"}:
        return f"G{name} {pos} {neg} VALUE = {{{expr}}}"
    if dialect == "hspice":
        return f"G{name} {pos} {neg} CUR='{expr}'"
    return f"B{name} {pos} {neg} I = {{{expr}}}"


def _render_reverse_recovery(project: DeviceProject, model_file: str) -> str:
    name = project.model_name
    params = _diode_parameters(project)
    forward_v = max(params["vf_v"] * 1.1, 0.8)
    reverse_v = min(params["bv_v"] * 0.25, 400.0)
    source_r = max(forward_v / max(params["if_ref_a"], 1e-9), 1e-3)
    return _clean(dedent(
        f"""\
        * {name} diode reverse-recovery starter deck
        .include {model_file}
        Vstep drive 0 PULSE({forward_v:g} {-reverse_v:g} 100n 10n 10n 1u 3u 1)
        Rsrc drive anode {source_r:g}
        X1 anode 0 {name}
        .tran 0 4.5u 0 1n
        .save V(anode) I(Vstep)
        .options plotwinsize=0 reltol=0.003 abstol=1n vntol=1u
        .end
        """
    ))


def _diode_parameters(project: DeviceProject) -> dict[str, float]:
    ratings = project.get_path("ratings", default={})
    paras = project.get_path("parasitics", default={})
    dynamic = project.get_path("dynamic", default={})
    forward = project.get_path("static", "forward_voltage", default={})
    leakage = project.get_path("static", "leakage", default={})
    capacitance = dynamic.get("junction_capacitance", {})
    recovery = dynamic.get("reverse_recovery", {})

    bv = _pick_number(ratings, ("vrrm_v", "vr_v", "vbr_v", "vdss_v"), 600.0)
    if_ref = _pick_number(ratings, ("if_av_a", "if_cont_a", "if_a", "id_cont_a"), 10.0)
    if_ref = _pick_number(forward, ("if_a", "test_current_a", "current_a"), if_ref)
    vf = _pick_number(forward, ("vf_v", "typ_v", "typ", "max_v", "max", "value_v", "value", "25"), 1.0)
    cj0 = _pick_number(capacitance, ("cj0_pf", "cj_pf", "ct_pf", "cjo_pf"), 50.0)
    trr = _pick_number(recovery, ("trr_ns", "trr_typ_ns", "trr_max_ns"), 20.0)
    qrr = _pick_number(recovery, ("qrr_nc", "qrr_typ_nc", "qrr_max_nc"), 0.0)
    irrm = _pick_number(recovery, ("irrm_a", "irrm_typ_a", "irrm_max_a"), math.nan)
    leakage_ua = _pick_number(leakage, ("ir_ua", "ir_max_ua", "irm_ua"), 10.0)

    ideality = _pick_number(project.get_path("models", "diode_basic", default={}), ("n", "ideality"), 1.8)
    rs = _pick_number(project.get_path("models", "diode_basic", default={}), ("rs_ohm",), math.nan)
    if not math.isfinite(rs):
        rs = max((vf / max(if_ref, 1e-9)) * 0.08, 1e-6)
    junction_v = max(vf - if_ref * rs, VT_25C)
    exponent = min(max(junction_v / (ideality * VT_25C), 1.0), 80.0)
    saturation = if_ref / max(math.exp(exponent) - 1.0, 1e-30)
    saturation = min(max(saturation, 1e-18), 1e-3)
    tt = max(qrr / max(if_ref, 1e-9), trr * 0.35) if qrr > 0 else trr
    if not math.isfinite(irrm) or irrm <= 0:
        irrm = (2.0 * qrr / max(trr, 1e-9)) if qrr > 0 else if_ref
    rr_scale = _clamp(irrm / max(if_ref, 1e-9), 0.05, 10.0)

    return {
        "bv_v": max(bv, 1.0),
        "if_ref_a": max(if_ref, 1e-6),
        "vf_v": max(vf, 0.05),
        "is_a": saturation,
        "n": max(ideality, 1.0),
        "rs_ohm": max(rs, 1e-6),
        "cjo_pf": max(cj0, 0.01),
        "m": 0.45,
        "vj_v": 0.8,
        "tt_ns": max(tt, 0.001),
        "tau_ns": max(tt, 0.001),
        "qrr_nc": max(qrr, 0.0),
        "trr_ns": max(trr, 0.001),
        "irrm_a": max(irrm, 0.0),
        "rr_scale": rr_scale,
        "ibv_a": max(leakage_ua * 1e-6, 1e-9),
        "la_nh": max(_pick_number(paras, ("la_nh", "lead_a_nh", "lp_nh"), 1.0), 1e-6),
        "lk_nh": max(_pick_number(paras, ("lk_nh", "lead_k_nh", "ln_nh"), 1.0), 1e-6),
        "ra_ohm": max(_pick_number(paras, ("ra_ohm", "lead_a_ohm"), 1e-3), 1e-6),
        "rk_ohm": max(_pick_number(paras, ("rk_ohm", "lead_k_ohm"), 1e-3), 1e-6),
    }


def _pick_number(data: Any, keys: tuple[str, ...], fallback: float) -> float:
    if isinstance(data, dict):
        for key in keys:
            if key in data:
                value = _number(data[key], math.nan)
                if math.isfinite(value):
                    return value
        return fallback
    return _number(data, fallback)


def _number(value: Any, fallback: float) -> float:
    if isinstance(value, bool):
        return fallback
    if isinstance(value, (int, float)):
        parsed = float(value)
        return parsed if math.isfinite(parsed) else fallback
    if isinstance(value, str):
        try:
            parsed = float(value.strip())
        except ValueError:
            return fallback
        return parsed if math.isfinite(parsed) else fallback
    if isinstance(value, list):
        for item in value:
            parsed = _number(item, math.nan)
            if math.isfinite(parsed):
                return parsed
    if isinstance(value, dict):
        for key in ("typ", "typical", "max", "25", "value"):
            if key in value:
                parsed = _number(value[key], math.nan)
                if math.isfinite(parsed):
                    return parsed
        for item in value.values():
            parsed = _number(item, math.nan)
            if math.isfinite(parsed):
                return parsed
    return fallback


def _clamp(value: float, low: float, high: float) -> float:
    return min(max(value, low), high)
