"""VDMOS compact model emitter."""

from __future__ import annotations

from textwrap import dedent

from ..dialects import SUPPORTED_DIALECTS, dialect_suffix
from ..plugins import emitter
from ..schema import DeviceProject


def _clean(text: str) -> str:
    return "\n".join(line.lstrip() for line in text.splitlines()).rstrip() + "\n"


@emitter("vdmos-static-fast")
class VdmosEmitter:
    name = "vdmos-static-fast"

    def emit(self, project: DeviceProject, dialect: str = "ltspice") -> dict[str, str]:
        if dialect not in SUPPORTED_DIALECTS:
            raise ValueError(f"unsupported VDMOS dialect: {dialect}")
        suffix = dialect_suffix(dialect)
        model_file = f"{project.model_name}_vdmos{suffix}.lib"
        return {
            model_file: _render_model(project, dialect),
            f"{project.model_name}_double_pulse_vdmos{suffix}.cir": _render_double_pulse(project, model_file, dialect),
        }


def _native_vdmos_dialect(dialect: str) -> bool:
    return dialect in {"ltspice", "ngspice"}


def _vdmos_parameters(project: DeviceProject) -> dict[str, float]:
    static = project.get_path("static", default={})
    dyn = project.get_path("dynamic", default={})
    caps = project.require_path("dynamic", "capacitance")
    body = dyn.get("body_diode", {})
    ratings = project.get_path("ratings", default={})

    vth = float(static.get("vgs_th_v", {}).get("25", 4.0))
    rds_mohm = float(static.get("rds_on_mohm", {}).get("25", 20.0))
    rds = rds_mohm * 1e-3
    rg = float(static.get("rg_int_ohm", 0.0) or 0.0)
    gfs = float(static.get("gfs_s", 0.0) or 0.0)
    kp = max(gfs * gfs * rds / 2, 0.1)
    rd = max(rds * 0.45, 1e-6)
    rs = max(rds * 0.45, 1e-6)

    ciss = [float(x) for x in caps["ciss_pf"]]
    coss = [float(x) for x in caps["coss_pf"]]
    crss = [float(x) for x in caps["crss_pf"]]
    cgdmax = max(crss)
    cgdmin = min(crss[-3:]) if len(crss) >= 3 else min(crss)
    cgd = max(crss[-1], 1.0)
    cgs = max(ciss[-1] - crss[-1], 1.0)
    cjo = max(coss[-1] - crss[-1], 1.0)
    vdss = float(ratings.get("vdss_v", 1200.0))
    qrr = float(body.get("qrr_nc", 0.0) or 0.0)
    trr = float(body.get("trr_ns", 20.0) or 20.0)
    tt = qrr / 68.0 if qrr > 0 else trr
    return {
        "vth": vth,
        "rds": rds,
        "rg": rg,
        "kp": kp,
        "rd": rd,
        "rs": rs,
        "cgdmax": cgdmax,
        "cgdmin": cgdmin,
        "cgd": cgd,
        "cgs": cgs,
        "cjo": cjo,
        "vdss": vdss,
        "tt": tt,
    }


def _render_model(project: DeviceProject, dialect: str) -> str:
    name = project.model_name + "_VDMOS"
    params = _vdmos_parameters(project)
    if not _native_vdmos_dialect(dialect):
        return _render_portable_fallback(project, dialect, params)

    note = "LTspice/ngspice native VDMOS starter. Fit against curves before design use."
    return _clean(dedent(
        f"""\
        * {name} generated by datasheet2spice
        * {note}
        * Pin order for M device: D G S
        .model {name} VDMOS(Rd={params["rd"]:g} Rs={params["rs"]:g} Rg={params["rg"]:g} Vto={params["vth"]:g} Kp={params["kp"]:g}
        + Cgdmax={params["cgdmax"]:g}p Cgdmin={params["cgdmin"]:g}p Cgs={params["cgs"]:g}p Cjo={params["cjo"]:g}p
        + Is=1e-12 N=2 Rb=1m Tt={params["tt"]:g}n BV={params["vdss"]:g} Ibv=30m)
        """
    ))


def _render_portable_fallback(project: DeviceProject, dialect: str, params: dict[str, float]) -> str:
    name = project.model_name + "_VDMOS"
    static = project.get_path("static", default={})
    paras = project.get_path("parasitics", default={})
    note = (
        f"{dialect} portable MOS fallback for the VDMOS starter. "
        "This is not a native VDMOS model; use the ABM emitter for transient capacitance fitting."
    )
    return _clean(dedent(
        f"""\
        * {name} generated by datasheet2spice
        * {note}
        * Pins: D G S
        .subckt {name} D G S PARAMS: LD={float(paras.get("ld_nh", 2.0))}n LS={float(paras.get("ls_nh", 1.0))}n LG={float(paras.get("lg_nh", 0.2))}n RGEXT={float(paras.get("rg_ext_ohm", 4.7))}
        Ld D d_int {{LD}}
        Lg G g_pad {{LG}}
        Ls S s_int {{LS}}
        Rg g_pad g_int {{RGEXT+{float(static.get("rg_int_ohm", 0.0) or 0.0):g}}}
        Rd d_int d_mos {params["rd"]:g}
        Rs s_mos s_int {params["rs"]:g}
        Mch d_mos g_int s_mos s_mos {name}_NMOS L=1u W=1u
        Cgs g_int s_int {params["cgs"]:g}p
        Cgd g_int d_int {params["cgd"]:g}p
        Cds d_int s_int {params["cjo"]:g}p
        Dbody s_int d_int {name}_DBODY
        Rgate_leak g_int s_int 1e12
        .model {name}_NMOS NMOS(Level=1 Vto={params["vth"]:g} Kp={params["kp"]:g} Lambda=0.002)
        .model {name}_DBODY D(Is=1e-12 N=2 Rs=31m Cjo={params["cjo"]:g}p M=0.45 Vj=1.0 Tt={params["tt"]:g}n BV={params["vdss"]:g} Ibv=30m)
        .ends {name}
        """
    ))


def _render_double_pulse(project: DeviceProject, model_file: str, dialect: str) -> str:
    name = project.model_name
    model = project.model_name + "_VDMOS"
    ratings = project.get_path("ratings", default={})
    paras = project.get_path("parasitics", default={})
    vbus = min(float(ratings.get("vdss_v", 1200)) * 2 / 3, 800.0)
    v_on = float(ratings.get("vgs_on_v", 18.0))
    v_off = float(ratings.get("vgs_off_v", -2.0))
    rg = float(paras.get("rg_ext_ohm", 4.7))
    device_line = f"M1 drain gate 0 {model}" if _native_vdmos_dialect(dialect) else f"XQ drain gate 0 {model}"
    return _clean(dedent(
        f"""\
        * {name} VDMOS low-side inductive double-pulse starter deck
        .include {model_file}
        Vbus bus 0 {vbus:g}
        Rload bus nload 20m
        Lload nload drain 250u
        Dfw drain bus DFAST
        .model DFAST D(Is=1e-15 N=1.5 Rs=20m Cjo=80p Tt=20n BV={float(ratings.get("vdss_v", 1200)):g} Ibv=1m)
        Vdrv gate_drv 0 PULSE({v_off:g} {v_on:g} 100n 5n 5n 21u 25u 2)
        Rdrv gate_drv gate {rg:g}
        {device_line}
        .tran 0 26.5u 0 1n
        .save V(drain) V(gate) V(gate_drv) I(Lload) I(Vbus)
        .options plotwinsize=0 reltol=0.003 abstol=1n vntol=1u
        .end
        """
    ))
