"""VDMOS compact model emitter."""

from __future__ import annotations

from textwrap import dedent

from ..plugins import emitter
from ..schema import DeviceProject


def _clean(text: str) -> str:
    return "\n".join(line.lstrip() for line in text.splitlines()).rstrip() + "\n"


@emitter("vdmos-static-fast")
class VdmosEmitter:
    name = "vdmos-static-fast"

    def emit(self, project: DeviceProject, dialect: str = "ltspice") -> dict[str, str]:
        if dialect not in {"ltspice", "ngspice", "common"}:
            raise ValueError(f"unsupported VDMOS dialect: {dialect}")
        suffix = "" if dialect == "common" else f"_{dialect}"
        model_file = f"{project.model_name}_vdmos{suffix}.lib"
        return {
            model_file: _render_model(project, dialect),
            f"{project.model_name}_double_pulse_vdmos{suffix}.cir": _render_double_pulse(project, model_file),
        }


def _render_model(project: DeviceProject, dialect: str) -> str:
    name = project.model_name + "_VDMOS"
    static = project.get_path("static", default={})
    dyn = project.get_path("dynamic", default={})
    caps = project.require_path("dynamic", "capacitance")
    body = dyn.get("body_diode", {})
    ratings = project.get_path("ratings", default={})

    vth = float(static.get("vgs_th_v", {}).get("25", 4.0))
    rds_mohm = float(static.get("rds_on_mohm", {}).get("25", 20.0))
    rds = rds_mohm * 1e-3
    rg = float(static.get("rg_int_ohm", 0.0) or 0.0)
    gfs = float(static.get("gfs_s", 0.0) or 0.0)
    kp = max(gfs * gfs * rds / 2, 0.1)
    rd = max(rds * 0.45, 1e-6)
    rs = max(rds * 0.45, 1e-6)

    vds = [float(x) for x in caps["vds_v"]]
    ciss = [float(x) for x in caps["ciss_pf"]]
    coss = [float(x) for x in caps["coss_pf"]]
    crss = [float(x) for x in caps["crss_pf"]]
    cgdmax = max(crss)
    cgdmin = min(crss[-3:]) if len(crss) >= 3 else min(crss)
    cgs = max(ciss[-1] - crss[-1], 1.0)
    cjo = max(coss[-1] - crss[-1], 1.0)
    vdss = float(ratings.get("vdss_v", 1200.0))
    qrr = float(body.get("qrr_nc", 0.0) or 0.0)
    trr = float(body.get("trr_ns", 20.0) or 20.0)
    tt = qrr / 68.0 if qrr > 0 else trr

    note = "LTspice/ngspice VDMOS starter. Fit against curves before design use."
    return _clean(dedent(
        f"""\
        * {name} generated by datasheet2spice
        * {note}
        * Pin order for M device: D G S
        .model {name} VDMOS(Rd={rd:g} Rs={rs:g} Rg={rg:g} Vto={vth:g} Kp={kp:g}
        + Cgdmax={cgdmax:g}p Cgdmin={cgdmin:g}p Cgs={cgs:g}p Cjo={cjo:g}p
        + Is=1e-12 N=2 Rb=1m Tt={tt:g}n BV={vdss:g} Ibv=30m)
        """
    ))


def _render_double_pulse(project: DeviceProject, model_file: str) -> str:
    name = project.model_name
    model = project.model_name + "_VDMOS"
    ratings = project.get_path("ratings", default={})
    paras = project.get_path("parasitics", default={})
    vbus = min(float(ratings.get("vdss_v", 1200)) * 2 / 3, 800.0)
    v_on = float(ratings.get("vgs_on_v", 18.0))
    v_off = float(ratings.get("vgs_off_v", -2.0))
    rg = float(paras.get("rg_ext_ohm", 4.7))
    return _clean(dedent(
        f"""\
        * {name} VDMOS low-side inductive double-pulse starter deck
        .include {model_file}
        Vbus bus 0 {vbus:g}
        Rload bus nload 20m
        Lload nload drain 250u
        Dfw drain bus DFAST
        .model DFAST D(Is=1e-15 N=1.5 Rs=20m Cjo=80p Tt=20n BV={float(ratings.get("vdss_v", 1200)):g} Ibv=1m)
        Vdrv gate_drv 0 PULSE({v_off:g} {v_on:g} 100n 5n 5n 21u 25u 2)
        Rdrv gate_drv gate {rg:g}
        M1 drain gate 0 {model}
        .tran 0 26.5u 0 1n
        .save V(drain) V(gate) V(gate_drv) I(Lload) I(Vbus)
        .options plotwinsize=0 reltol=0.003 abstol=1n vntol=1u
        .end
        """
    ))
